services:
  user-service:
    build: ./user-service
    ports:
      - '8080:8080'
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/codepilot
    depends_on:
      - redis
      - mongo

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - '3001:3001'
    volumes:
      - ./auth-service/src:/app/src  
      - /app/node_modules
    environment:
      - PORT=3001
    depends_on:
      - mongo
    env_file:
      - ./auth-service/.env
  
  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - '3002:3002'
    volumes:
      - ./ai-service/src:/app/src  
      - /app/node_modules
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/codepilot
    depends_on:
      - mongo
      - redis
    env_file:
      - ./ai-service/.env

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - '8081:8081'
    volumes:
      - ./api-gateway/src:/app/src
      - /app/node_modules
    environment:
      - PORT=8081
      - REDIS_URL=redis://redis:6379
    depends_on:
      - auth-service
      - ai-service
      - user-service
    env_file:
      - ./api-gateway/.env

  redis:
    image: redis:7

  kafka:
    image: bitnami/kafka:3.6
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
    volumes:
      - kafka-data:/bitnami/kafka/data

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  kafka-data:
